application: vtonemusic
version: 1
runtime: php
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /peeps
  static_dir: peeps
  application_readable: true

- url: /photo
  static_dir: photo
  application_readable: true

- url: /FlexSlider
  static_dir: FlexSlider

- url: /links
  static_dir: links
  application_readable: true

- url: /audio
  static_dir: audio
  application_readable: true

- url: /logo\.png
  static_files: logo.png
  upload: logo\.png

- url: /main\.css
  static_files: main.css
  upload: main\.css

- url: /stripebg\.png
  static_files: stripebg.png
  upload: stripebg\.png

- url: /audio.php
  script: audio.php

- url: /photo.php
  script: photo.php

- url: /.*
  script: main.php
